owner: ajmarkow
repo: uptime

sites:
  - name: AJM.CODES
    url: https://ajm.codes
  - name: BESZEL.AJ-CLOUD.CC
    url: https://beszel.aj-cloud.cc
  - name: BIRDNET.AJ-CLOUD.CC
    url: https://birdnet.aj-cloud.cc
    expectedStatusCodes:
      - 401
  - name: KEEPER.AJ-CLOUD.CC
    url: https://keeper.aj-cloud.cc
  - name: L.AJM.CODES
    url: https://l.ajm.codes/dashboard
  - name: N8N.AJ-CLOUD.CC
    url: https://n8n.aj-cloud.cc
  - name: PASEO.AJ-CLOUD.CC
    url: https://paseo.aj-cloud.cc/api/health

status-website:
  cname: uptime.ajm.codes
  # baseUrl: /uptime
  name: AJ Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
